pool:
  vmImage: "ubuntu-latest"

resources:
  - repo: self

trigger:
  - none
  
stages:
  - stage: buildanddeploy
    variables:
      location: "uksouth"
      templateFile: "$(System.DefaultWorkingDirectory)/landing-zone/networks.bicep"

    jobs:
    - job:
      displayName: Build and Deploy Landing Zone
      steps:

      - task: UseNode@1
        displayName: Use Node 17.x
        inputs:
          version: 17.x      

      - task: Npm@1
        displayName: 'Install App Dependencies'
        inputs:
          command: install
          workingDir: '$(System.DefaultWorkingDirectory)'
          verbose: false

      - script: npm run update-naming
        displayName: 'Update Naming Convention'

      - script: npm run config-to-json
        displayName: 'Convert YAML to JSON'
     
      - task: AzureCLI@2
        displayName: Deploy Landing Zone
        inputs:
          azureSubscription: "sub1-connection"
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment sub create --location $(location) --template-file $(templateFile)