$schema: ./schemas/resource-groups-config-schema.json

resourceGroups:
  - name: tom-rg-core-uks
    location: uksouth
    subscriptionId: e19465a6-ad97-460b-ad93-c8dcf29bc26e
    tags:
      owner: tom
      project: landing-zone
  
  - name: tom-rg-hub-net
    location: uksouth
    subscriptionId: e19465a6-ad97-460b-ad93-c8dcf29bc26e
    tags:
      owner: tom
      project: landing-zone    

  - name: tom-rg-core-net
    location: uksouth
    subscriptionId: e19465a6-ad97-460b-ad93-c8dcf29bc26e
    tags:
      owner: tom
      project: landing-zone

  - name: tom-rg-prod-net
    location: uksouth
    subscriptionId: bf69f0e9-5eed-42f8-b9db-fbd125c860ce
    tags:
      owner: tom
      project: landing-zone

  - name: tom-rg-preprod-net
    location: uksouth
    subscriptionId: bf69f0e9-5eed-42f8-b9db-fbd125c860ce
    tags:
      owner: tom
      project: landing-zone

  - name: tom-rg-dev-net
    location: uksouth
    subscriptionId: bf69f0e9-5eed-42f8-b9db-fbd125c860ce