name: Deploy Landing Zone
on: [workflow_dispatch]

permissions: read-all|write-all

jobs: 
  deploy:
    name: 'LZ Deployment'
    runs-on: ubuntu-latest
    environment: ingisub1

    steps:
    - uses: actions/checkout@v2
    - name: Use Nodejs 17
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
        cache: 'npm'
      
    - name: Install Prereqs
      run: npm install

    - name: Update Naming Convention
      run: npm run update-naming

    - name: Convert YAML to JSON
      run: npm run config-to-json

      # Log into Azure
    - uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

      # Deploy Using npm package
    - name: Deploy Landing Zone
      run: |
          az account show
          az deployment sub create --location uksouth --template-file landing-zone\resource-groups.bicep
          az deployment sub create --location uksouth --template-file landing-zone\networks.bicep
          az deployment sub create --location uksouth --template-file landing-zone\core.bicep -p vmAdminPassword=${{ secrets.AZURE_VM_CREDS }}
